### ISSUE TITLE
(Another) problem in convert.py

### ISSUE THREAD

**Issue by sashavor** [javirk/Person_remover#10]
Hi,

When I try to run convert.py, I get:

```
I1103 08:21:42.501203 139996653496128 utils.py:45] yolo_output_2/conv2d_74 bias
Traceback (most recent call last):
  File "convert.py", line 34, in <module>
    app.run(main)
  File "/python3.6/site-packages/absl/app.py", line 300, in run
    _run_main(main, args)
  File "/python3.6/site-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "convert.py", line 21, in main
    load_darknet_weights(yolo, FLAGS.weights, FLAGS.tiny)
  File "/Person_remover/yolo/yolov3/utils.py", line 74, in load_darknet_weights
    assert len(wf.read()) == 0, 'failed to read all data'
AssertionError: failed to read all data
```

any ideas?

**Comment by sashavor** [comment]
Found the solution here:
https://www.gitmemory.com/issue/YunYang1994/TensorFlow2.0-Examples/13/517911887
(simply commenting out the assert statement).

**Comment by javirk** [comment]
Hi @sashavor, thank you for the question and the solution. I will check it out and see if it's safe to change that assert statement with a warning or something.
