### ISSUE TITLE
Not able to generate outputs

### ISSUE THREAD

**Issue by Kunika21** [javirk/Person_remover#5]
I am able to run person_remover.py . It printing some arrays in console but isn't saving any figures to output dir. Pls suggest a soln.

**Comment by javirk** [comment]
It is working for me with the default configuration. Could you give more specific information on the errors you are getting (if any)?

**Comment by Kunika21** [comment]
Following is the error I am getting:

Traceback (most recent call last):
  File "person_remover.py", line 38, in <module>
    yolo = prepare_detector()
  File "/content/Person_remover/yolo/detect.py", line 18, in prepare_detector
    yolo.load_weights(weights)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/training.py", line 162, in load_weights
    return super(Model, self).load_weights(filepath, by_name)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/network.py", line 1398, in load_weights
    status.assert_nontrivial_match()
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/training/tracking/util.py", line 917, in assert_nontrivial_match
    return self.assert_consumed()
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/training/tracking/util.py", line 894, in assert_consumed
    (unused_attributes,))
AssertionError: Some objects had attributes which were not restored: {<tf.Variable 'conv2d/kernel:0' shape=(3, 3, 3, 32) dtype=float32, numpy=
array([[[[-7.05286860e-04, -8.05389583e-02, -6.61824942e-02,
           4.80058044e-02, -7.62826502e-02,  5.86763620e-02,
           6.55027479e-02,  2.64812559e-02,  5.13334423e-02,
           1.16266206e-01, -7.61363879e-02, -9.98185575e-02,
           1.35706365e-03, -2.72979960e-02,  1.35508552e-01,
           2.85753310e-02, -5.48837110e-02,  6.50999844e-02,
           8.31194222e-02, -9.33649912e-02,  1.10498801e-01,
          -1.19732499e-01,  1.25158235e-01, -3.07219103e-02,
           1.08983666e-02,  4.46056426e-02, -7.79754072e-02,
           4.69649881e-02,  4.51817364e-02, -6.42157346e-02,
           1.11913145e-01,  5.78417927e-02],
         [ 3.74193490e-02, -2.45500058e-02,  1.38875097e-02,
           4.65825647e-02, -9.81163904e-02,  1.10713497e-01,
          -8.46711546e-02, -1.23213805e-01,  9.00346935e-02,
          -5.75840473e-02,  7.90383667e-02,  1.15598336e-01,
          -7.04545975e-02, -1.31256580e-01,  3.20658088e-02,
          -1.59845352e-02, -3.89964432e-02, -1.10735387e-01,
           9.17940438e-02,  9.86699462e-02, -4.85336781e-03,
           5.50033152e-02,  8.70966166e-02,  1.23643085e-01,
          -1.27934903e-01,  5.49348742e-02,  7.24025071e-02,
           4.55670059e-03, -7.04619735e-02,  8.92329663e-02,
          -5.90388104e-02, -5.74967563e-02],
         [ 1.17811710e-02, -3.74758393e-02,  8.33766460e-02,
          -2.56854594e-02, -1.18946895e-01, -6.14592955e-02,
           1.16072997e-01, -5.13701886e-02, -2.21078098e-03,
           3.78623009e-02, -5.92656434e-03,  2.01924741e-02,
          -9.10230875e-02,  7.92924613e-02, -1.13067910e-01,
          -8.36447924e-02, -1.00955486e-01,  8.14680308e-02,
           1.31164864e-01,  3.91563922e-02, -1.12812273e-01,
           1.29137918e-01, -9.18676555e-02, -1.71576962e-02,
          -4.02657688e-03, -4.93321940e-02, -6.79263845e-02,
          -8.57582390e-02, -1.33396581e-01, -4.77216989e-02,
          -4.63932604e-02, -1.32539481e-01]],

        [[-1.25640184e-01,  2.98653692e-02, -1.76673234e-02,
           7.40247220e-02, -8.13863277e-02, -4.71209511e-02,
          -2.81762630e-02,  4.74542528e-02, -3.67864817e-02,
           5.66151738e-03, -7.49273300e-02,  1.23418823e-01,
          -1.21287420e-01,  1.19170293e-01,  5.79065531e-02,
          -9.68945324e-02, -3.35474238e-02,  1.08652040e-01,
           1.36788622e-01,  1.29259869e-01,  1.34562552e-02,
          -1.10154182e-01, -4.31177765e-02, -6.34081811e-02,
          -6.16385564e-02, -9.15939510e-02,  4.04699147e-02,
           8.57953578e-02, -1.32732987e-01,  2.24898309e-02,
          -3.92586887e-02, -4.02188897e-02],
         [-9.05874372e-03, -5.89442253e-03, -1.11337282e-01,
           1.23639897e-01, -1.08974546e-01,  2.21077353e-02,
           1.29917100e-01,  1.17475405e-01, -5.63411638e-02,
           5.62471300e-02,  1.25576600e-01, -3.00528929e-02,
           5.39527982e-02,  1.25964567e-01, -1.21518254e-01,
           7.70440996e-02,  9.97101367e-02,  6.92859143e-02,
           1.36248454e-01, -1.11650527e-02, -7.48169646e-02,
           7.06019998e-03, -4.07930464e-02,  2.28003263e-02,
           1.05080083e-01,  1.34709492e-01,  1.76454484e-02,
          -4.80940491e-02,  4.82748300e-02,  1.27935275e-01,
          -1.15317881e-01,  6.21230900e-03],
         [ 6.96253031e-02, -6.15839660e-02,  8.28827173e-02,
           2.27040797e-02,  1.36388287e-01,  1.13028869e-01,
          -1.23644665e-01,  7.90336281e-02,  1.00915387e-01,
           1.26195475e-01,  5.68111837e-02,  3.60755026e-02,
           5.52888960e-02,  1.04478896e-02, -1.36931226e-01,
          -2.50716507e-02, -1.84201598e-02, -1.39993504e-02,
          -6.61143810e-02, -8.30215365e-02,  2.80274600e-02,
          -3.61328274e-02,  1.25569150e-01,  5.08805662e-02,
          -1.36788756e-01, -9.45070833e-02,  1.24870941e-01,
          -6.99184835e-02,  4.05593216e-02,  1.17724612e-01,
           4.40301001e-03,  4.68420833e-02]],

        [[ 1.22260734e-01,  1.17186949e-01, -1.28446072e-01,
           8.98254067e-02,  1.30781189e-01, -9.71307904e-02,
          -1.30157128e-01,  5.25365025e-02,  8.55027288e-02,
           7.36195892e-02,  5.21382242e-02,  5.51276058e-02,
          -7.28948563e-02,  3.03880274e-02,  1.40916556e-02,
           1.84723735e-02, -1.38003796e-01, -7.09837750e-02,
           4.91091609e-02,  3.32777351e-02, -6.11202419e-03,
          -3.95707265e-02, -7.27836415e-02,  2.83725709e-02,
          -8.74803141e-02, -1.08667277e-01,  1.69960707e-02,
           1.26064166e-01, -5.74735254e-02, -2.04539746e-02,
           2.18076855e-02,  1.01017877e-01],
         [-4.90651354e-02, -9.15263295e-02, -1.08576953e-01,
           2.33392417e-02, -1.15583390e-01,  5.60518354e-02,
           1.28824264e-02,  9.45371240e-02, -4.77087647e-02,
          -1.76495314e-03,  1.05755717e-01,  1.12688228e-01,
          -6.96494505e-02, -1.04351476e-01, -1.09657846e-01,
          -9.54841673e-02,  3.97268236e-02, -9.60418731e-02,
          -5.89052141e-02,  1.02174386e-01,  8.49785954e-02,
           9.50295478e-02,  1.09188065e-01, -5.51544502e-02,
          -7.62238801e-02,  1.26478925e-01,  6.76610768e-02,
           7.15120286e-02, -5.33290505e-02,  1.29089192e-01,
          -1.25343248e-01, -4.96262982e-02],
         [ 1.33568212e-01,  1.19960025e-01,  1.15879476e-02,
           4.06815261e-02, -4.39742953e-02, -3.58538330e-03,
           1.26259193e-01,  2.90782750e-02, -1.19444326e-01,
          -5.06583601e-02,  6.49650395e-03,  5.11552244e-02,
          -8.07657838e-03, -1.15868777e-01, -1.21684358e-01,
          -1.17932178e-01,  1.02520436e-02, -9.48854983e-02,
          -1.06537446e-01, -6.94688335e-02,  2.28475034e-02,
          -1.24576628e-01, -8.20208341e-02, -5.17244488e-02,
          -1.17515966e-01, -1.11440569e-02, -1.08317040e-01,
           1.19888052e-01,  8.07241797e-02, -1.19611509e-01,
           4.89917248e-02, -1.50492787e-02]]],


Like this there are many arrays

**Comment by Kunika21** [comment]
Sorry, for inconvenience. This got solved. However, I tried removing cars and cycles as well, but it doesn't remove it completely, rather it just blocks it with black patches. How can i get the bg b seen.

**Comment by Kunika21** [comment]
This got solved

**Comment by javirk** [comment]
For future reference, did you have to change anything in the code?

**Comment by Kunika21** [comment]
Nothing major as such, my pix2pix script was not running because I tried to run it on tensorflow_cpu beta. It will be great if you mention in readme that gpu is explicitly a necessity. 
And, the default path for outputs is ./output/ ,set in parser. It will be a positive if u can just do os.makedir with a flag in accordance with parser in remover.py. Also, in https://github.com/javirk/Person_remover/blob/master/yolo/convert.py for checkpoints you can just use os.makedir to make dir there as well.
And the following error I guess was caused perhaps because my file got corrupted. It got solved when I downloaded and unzipped again.

That's All.

> Following is the error I am getting:
> 
> Traceback (most recent call last):
> File "person_remover.py", line 38, in
> yolo = prepare_detector()
> File "/content/Person_remover/yolo/detect.py", line 18, in prepare_detector
> yolo.load_weights(weights)
> File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/training.py", line 162, in load_weights
> return super(Model, self).load_weights(filepath, by_name)
> File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/network.py", line 1398, in load_weights
> status.assert_nontrivial_match()
> File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/training/tracking/util.py", line 917, in assert_nontrivial_match
> return self.assert_consumed()
> File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/training/tracking/util.py", line 894, in assert_consumed
> (unused_attributes,))
> AssertionError: Some objects had attributes which were not restored: {<tf.Variable 'conv2d/kernel:0' shape=(3, 3, 3, 32) dtype=float32, numpy=
> array([[[[-7.05286860e-04, -8.05389583e-02, -6.61824942e-02,
> 4.80058044e-02, -7.62826502e-02, 5.86763620e-02,
> 6.55027479e-02, 2.64812559e-02, 5.13334423e-02,
> 1.16266206e-01, -7.61363879e-02, -9.98185575e-02,
> 1.35706365e-03, -2.72979960e-02, 1.35508552e-01,
> 2.85753310e-02, -5.48837110e-02, 6.50999844e-02,
> 8.31194222e-02, -9.33649912e-02, 1.10498801e-01,
> -1.19732499e-01, 1.25158235e-01, -3.07219103e-02,
> 1.08983666e-02, 4.46056426e-02, -7.79754072e-02,
> 4.69649881e-02, 4.51817364e-02, -6.42157346e-02,
> 1.11913145e-01, 5.78417927e-02],
> [ 3.74193490e-02, -2.45500058e-02, 1.38875097e-02,
> 4.65825647e-02, -9.81163904e-02, 1.10713497e-01,
> -8.46711546e-02, -1.23213805e-01, 9.00346935e-02,
> -5.75840473e-02, 7.90383667e-02, 1.15598336e-01,
> -7.04545975e-02, -1.31256580e-01, 3.20658088e-02,
> -1.59845352e-02, -3.89964432e-02, -1.10735387e-01,
> 9.17940438e-02, 9.86699462e-02, -4.85336781e-03,
> 5.50033152e-02, 8.70966166e-02, 1.23643085e-01,
> -1.27934903e-01, 5.49348742e-02, 7.24025071e-02,
> 4.55670059e-03, -7.04619735e-02, 8.92329663e-02,
> -5.90388104e-02, -5.74967563e-02],
> [ 1.17811710e-02, -3.74758393e-02, 8.33766460e-02,
> -2.56854594e-02, -1.18946895e-01, -6.14592955e-02,
> 1.16072997e-01, -5.13701886e-02, -2.21078098e-03,
> 3.78623009e-02, -5.92656434e-03, 2.01924741e-02,
> -9.10230875e-02, 7.92924613e-02, -1.13067910e-01,
> -8.36447924e-02, -1.00955486e-01, 8.14680308e-02,
> 1.31164864e-01, 3.91563922e-02, -1.12812273e-01,
> 1.29137918e-01, -9.18676555e-02, -1.71576962e-02,
> -4.02657688e-03, -4.93321940e-02, -6.79263845e-02,
> -8.57582390e-02, -1.33396581e-01, -4.77216989e-02,
> -4.63932604e-02, -1.32539481e-01]],
> 
> ```
>     [[-1.25640184e-01,  2.98653692e-02, -1.76673234e-02,
>        7.40247220e-02, -8.13863277e-02, -4.71209511e-02,
>       -2.81762630e-02,  4.74542528e-02, -3.67864817e-02,
>        5.66151738e-03, -7.49273300e-02,  1.23418823e-01,
>       -1.21287420e-01,  1.19170293e-01,  5.79065531e-02,
>       -9.68945324e-02, -3.35474238e-02,  1.08652040e-01,
>        1.36788622e-01,  1.29259869e-01,  1.34562552e-02,
>       -1.10154182e-01, -4.31177765e-02, -6.34081811e-02,
>       -6.16385564e-02, -9.15939510e-02,  4.04699147e-02,
>        8.57953578e-02, -1.32732987e-01,  2.24898309e-02,
>       -3.92586887e-02, -4.02188897e-02],
>      [-9.05874372e-03, -5.89442253e-03, -1.11337282e-01,
>        1.23639897e-01, -1.08974546e-01,  2.21077353e-02,
>        1.29917100e-01,  1.17475405e-01, -5.63411638e-02,
>        5.62471300e-02,  1.25576600e-01, -3.00528929e-02,
>        5.39527982e-02,  1.25964567e-01, -1.21518254e-01,
>        7.70440996e-02,  9.97101367e-02,  6.92859143e-02,
>        1.36248454e-01, -1.11650527e-02, -7.48169646e-02,
>        7.06019998e-03, -4.07930464e-02,  2.28003263e-02,
>        1.05080083e-01,  1.34709492e-01,  1.76454484e-02,
>       -4.80940491e-02,  4.82748300e-02,  1.27935275e-01,
>       -1.15317881e-01,  6.21230900e-03],
>      [ 6.96253031e-02, -6.15839660e-02,  8.28827173e-02,
>        2.27040797e-02,  1.36388287e-01,  1.13028869e-01,
>       -1.23644665e-01,  7.90336281e-02,  1.00915387e-01,
>        1.26195475e-01,  5.68111837e-02,  3.60755026e-02,
>        5.52888960e-02,  1.04478896e-02, -1.36931226e-01,
>       -2.50716507e-02, -1.84201598e-02, -1.39993504e-02,
>       -6.61143810e-02, -8.30215365e-02,  2.80274600e-02,
>       -3.61328274e-02,  1.25569150e-01,  5.08805662e-02,
>       -1.36788756e-01, -9.45070833e-02,  1.24870941e-01,
>       -6.99184835e-02,  4.05593216e-02,  1.17724612e-01,
>        4.40301001e-03,  4.68420833e-02]],
> 
>     [[ 1.22260734e-01,  1.17186949e-01, -1.28446072e-01,
>        8.98254067e-02,  1.30781189e-01, -9.71307904e-02,
>       -1.30157128e-01,  5.25365025e-02,  8.55027288e-02,
>        7.36195892e-02,  5.21382242e-02,  5.51276058e-02,
>       -7.28948563e-02,  3.03880274e-02,  1.40916556e-02,
>        1.84723735e-02, -1.38003796e-01, -7.09837750e-02,
>        4.91091609e-02,  3.32777351e-02, -6.11202419e-03,
>       -3.95707265e-02, -7.27836415e-02,  2.83725709e-02,
>       -8.74803141e-02, -1.08667277e-01,  1.69960707e-02,
>        1.26064166e-01, -5.74735254e-02, -2.04539746e-02,
>        2.18076855e-02,  1.01017877e-01],
>      [-4.90651354e-02, -9.15263295e-02, -1.08576953e-01,
>        2.33392417e-02, -1.15583390e-01,  5.60518354e-02,
>        1.28824264e-02,  9.45371240e-02, -4.77087647e-02,
>       -1.76495314e-03,  1.05755717e-01,  1.12688228e-01,
>       -6.96494505e-02, -1.04351476e-01, -1.09657846e-01,
>       -9.54841673e-02,  3.97268236e-02, -9.60418731e-02,
>       -5.89052141e-02,  1.02174386e-01,  8.49785954e-02,
>        9.50295478e-02,  1.09188065e-01, -5.51544502e-02,
>       -7.62238801e-02,  1.26478925e-01,  6.76610768e-02,
>        7.15120286e-02, -5.33290505e-02,  1.29089192e-01,
>       -1.25343248e-01, -4.96262982e-02],
>      [ 1.33568212e-01,  1.19960025e-01,  1.15879476e-02,
>        4.06815261e-02, -4.39742953e-02, -3.58538330e-03,
>        1.26259193e-01,  2.90782750e-02, -1.19444326e-01,
>       -5.06583601e-02,  6.49650395e-03,  5.11552244e-02,
>       -8.07657838e-03, -1.15868777e-01, -1.21684358e-01,
>       -1.17932178e-01,  1.02520436e-02, -9.48854983e-02,
>       -1.06537446e-01, -6.94688335e-02,  2.28475034e-02,
>       -1.24576628e-01, -8.20208341e-02, -5.17244488e-02,
>       -1.17515966e-01, -1.11440569e-02, -1.08317040e-01,
>        1.19888052e-01,  8.07241797e-02, -1.19611509e-01,
>        4.89917248e-02, -1.50492787e-02]]],
> ```
> 
> Like this there are many arrays

**Comment by naganikshith04** [comment]
> Nothing major as such, my pix2pix script was not running because I tried to run it on tensorflow_cpu beta. It will be great if you mention in readme that gpu is explicitly a necessity.
> And, the default path for outputs is ./output/ ,set in parser. It will be a positive if u can just do os.makedir with a flag in accordance with parser in remover.py. Also, in https://github.com/javirk/Person_remover/blob/master/yolo/convert.py for checkpoints you can just use os.makedir to make dir there as well.
> And the following error I guess was caused perhaps because my file got corrupted. It got solved when I downloaded and unzipped again.
> 
> That's All.
> 
> > Following is the error I am getting:
> > Traceback (most recent call last):
> > File "person_remover.py", line 38, in
> > yolo = prepare_detector()
> > File "/content/Person_remover/yolo/detect.py", line 18, in prepare_detector
> > yolo.load_weights(weights)
> > File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/training.py", line 162, in load_weights
> > return super(Model, self).load_weights(filepath, by_name)
> > File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/network.py", line 1398, in load_weights
> > status.assert_nontrivial_match()
> > File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/training/tracking/util.py", line 917, in assert_nontrivial_match
> > return self.assert_consumed()
> > File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/training/tracking/util.py", line 894, in assert_consumed
> > (unused_attributes,))
> > AssertionError: Some objects had attributes which were not restored: {<tf.Variable 'conv2d/kernel:0' shape=(3, 3, 3, 32) dtype=float32, numpy=
> > array([[[[-7.05286860e-04, -8.05389583e-02, -6.61824942e-02,
> > 4.80058044e-02, -7.62826502e-02, 5.86763620e-02,
> > 6.55027479e-02, 2.64812559e-02, 5.13334423e-02,
> > 1.16266206e-01, -7.61363879e-02, -9.98185575e-02,
> > 1.35706365e-03, -2.72979960e-02, 1.35508552e-01,
> > 2.85753310e-02, -5.48837110e-02, 6.50999844e-02,
> > 8.31194222e-02, -9.33649912e-02, 1.10498801e-01,
> > -1.19732499e-01, 1.25158235e-01, -3.07219103e-02,
> > 1.08983666e-02, 4.46056426e-02, -7.79754072e-02,
> > 4.69649881e-02, 4.51817364e-02, -6.42157346e-02,
> > 1.11913145e-01, 5.78417927e-02],
> > [ 3.74193490e-02, -2.45500058e-02, 1.38875097e-02,
> > 4.65825647e-02, -9.81163904e-02, 1.10713497e-01,
> > -8.46711546e-02, -1.23213805e-01, 9.00346935e-02,
> > -5.75840473e-02, 7.90383667e-02, 1.15598336e-01,
> > -7.04545975e-02, -1.31256580e-01, 3.20658088e-02,
> > -1.59845352e-02, -3.89964432e-02, -1.10735387e-01,
> > 9.17940438e-02, 9.86699462e-02, -4.85336781e-03,
> > 5.50033152e-02, 8.70966166e-02, 1.23643085e-01,
> > -1.27934903e-01, 5.49348742e-02, 7.24025071e-02,
> > 4.55670059e-03, -7.04619735e-02, 8.92329663e-02,
> > -5.90388104e-02, -5.74967563e-02],
> > [ 1.17811710e-02, -3.74758393e-02, 8.33766460e-02,
> > -2.56854594e-02, -1.18946895e-01, -6.14592955e-02,
> > 1.16072997e-01, -5.13701886e-02, -2.21078098e-03,
> > 3.78623009e-02, -5.92656434e-03, 2.01924741e-02,
> > -9.10230875e-02, 7.92924613e-02, -1.13067910e-01,
> > -8.36447924e-02, -1.00955486e-01, 8.14680308e-02,
> > 1.31164864e-01, 3.91563922e-02, -1.12812273e-01,
> > 1.29137918e-01, -9.18676555e-02, -1.71576962e-02,
> > -4.02657688e-03, -4.93321940e-02, -6.79263845e-02,
> > -8.57582390e-02, -1.33396581e-01, -4.77216989e-02,
> > -4.63932604e-02, -1.32539481e-01]],
> > ```
> >     [[-1.25640184e-01,  2.98653692e-02, -1.76673234e-02,
> >        7.40247220e-02, -8.13863277e-02, -4.71209511e-02,
> >       -2.81762630e-02,  4.74542528e-02, -3.67864817e-02,
> >        5.66151738e-03, -7.49273300e-02,  1.23418823e-01,
> >       -1.21287420e-01,  1.19170293e-01,  5.79065531e-02,
> >       -9.68945324e-02, -3.35474238e-02,  1.08652040e-01,
> >        1.36788622e-01,  1.29259869e-01,  1.34562552e-02,
> >       -1.10154182e-01, -4.31177765e-02, -6.34081811e-02,
> >       -6.16385564e-02, -9.15939510e-02,  4.04699147e-02,
> >        8.57953578e-02, -1.32732987e-01,  2.24898309e-02,
> >       -3.92586887e-02, -4.02188897e-02],
> >      [-9.05874372e-03, -5.89442253e-03, -1.11337282e-01,
> >        1.23639897e-01, -1.08974546e-01,  2.21077353e-02,
> >        1.29917100e-01,  1.17475405e-01, -5.63411638e-02,
> >        5.62471300e-02,  1.25576600e-01, -3.00528929e-02,
> >        5.39527982e-02,  1.25964567e-01, -1.21518254e-01,
> >        7.70440996e-02,  9.97101367e-02,  6.92859143e-02,
> >        1.36248454e-01, -1.11650527e-02, -7.48169646e-02,
> >        7.06019998e-03, -4.07930464e-02,  2.28003263e-02,
> >        1.05080083e-01,  1.34709492e-01,  1.76454484e-02,
> >       -4.80940491e-02,  4.82748300e-02,  1.27935275e-01,
> >       -1.15317881e-01,  6.21230900e-03],
> >      [ 6.96253031e-02, -6.15839660e-02,  8.28827173e-02,
> >        2.27040797e-02,  1.36388287e-01,  1.13028869e-01,
> >       -1.23644665e-01,  7.90336281e-02,  1.00915387e-01,
> >        1.26195475e-01,  5.68111837e-02,  3.60755026e-02,
> >        5.52888960e-02,  1.04478896e-02, -1.36931226e-01,
> >       -2.50716507e-02, -1.84201598e-02, -1.39993504e-02,
> >       -6.61143810e-02, -8.30215365e-02,  2.80274600e-02,
> >       -3.61328274e-02,  1.25569150e-01,  5.08805662e-02,
> >       -1.36788756e-01, -9.45070833e-02,  1.24870941e-01,
> >       -6.99184835e-02,  4.05593216e-02,  1.17724612e-01,
> >        4.40301001e-03,  4.68420833e-02]],
> > 
> >     [[ 1.22260734e-01,  1.17186949e-01, -1.28446072e-01,
> >        8.98254067e-02,  1.30781189e-01, -9.71307904e-02,
> >       -1.30157128e-01,  5.25365025e-02,  8.55027288e-02,
> >        7.36195892e-02,  5.21382242e-02,  5.51276058e-02,
> >       -7.28948563e-02,  3.03880274e-02,  1.40916556e-02,
> >        1.84723735e-02, -1.38003796e-01, -7.09837750e-02,
> >        4.91091609e-02,  3.32777351e-02, -6.11202419e-03,
> >       -3.95707265e-02, -7.27836415e-02,  2.83725709e-02,
> >       -8.74803141e-02, -1.08667277e-01,  1.69960707e-02,
> >        1.26064166e-01, -5.74735254e-02, -2.04539746e-02,
> >        2.18076855e-02,  1.01017877e-01],
> >      [-4.90651354e-02, -9.15263295e-02, -1.08576953e-01,
> >        2.33392417e-02, -1.15583390e-01,  5.60518354e-02,
> >        1.28824264e-02,  9.45371240e-02, -4.77087647e-02,
> >       -1.76495314e-03,  1.05755717e-01,  1.12688228e-01,
> >       -6.96494505e-02, -1.04351476e-01, -1.09657846e-01,
> >       -9.54841673e-02,  3.97268236e-02, -9.60418731e-02,
> >       -5.89052141e-02,  1.02174386e-01,  8.49785954e-02,
> >        9.50295478e-02,  1.09188065e-01, -5.51544502e-02,
> >       -7.62238801e-02,  1.26478925e-01,  6.76610768e-02,
> >        7.15120286e-02, -5.33290505e-02,  1.29089192e-01,
> >       -1.25343248e-01, -4.96262982e-02],
> >      [ 1.33568212e-01,  1.19960025e-01,  1.15879476e-02,
> >        4.06815261e-02, -4.39742953e-02, -3.58538330e-03,
> >        1.26259193e-01,  2.90782750e-02, -1.19444326e-01,
> >       -5.06583601e-02,  6.49650395e-03,  5.11552244e-02,
> >       -8.07657838e-03, -1.15868777e-01, -1.21684358e-01,
> >       -1.17932178e-01,  1.02520436e-02, -9.48854983e-02,
> >       -1.06537446e-01, -6.94688335e-02,  2.28475034e-02,
> >       -1.24576628e-01, -8.20208341e-02, -5.17244488e-02,
> >       -1.17515966e-01, -1.11440569e-02, -1.08317040e-01,
> >        1.19888052e-01,  8.07241797e-02, -1.19611509e-01,
> >        4.89917248e-02, -1.50492787e-02]]],
> > ```
> > 
> > 
> > Like this there are many arrays

Even im getting the same thing like black patches where the person is detected.I m running it on google colab ..what should i do any help?
![person](https://user-images.githubusercontent.com/41370850/90245933-36b88100-de51-11ea-8c97-533eadb79b83.jpg)

**Comment by Kunika21** [comment]
@naganikshith04 this indicates that your yolo arch is running but your code is getting stopped at pix to pix. I faced this problem because i tried to run it on cpu, however the code explicitly required a gpu and cuda compiled packages. I suggest you check on this. More then this you can just sneak into ur pix2pix folder and check the files getting called there. If there is some path issue, that might be creating the problem.

**Comment by naganikshith04** [comment]
> @naganikshith04 this indicates that your yolo arch is running but your code is getting stopped at pix to pix. I faced this problem because i tried to run it on cpu, however the code explicitly required a gpu and cuda compiled packages. I suggest you check on this. More then this you can just sneak into ur pix2pix folder and check the files getting called there. If there is some path issue, that might be creating the problem.

@Kunika21 thankyou very much i will try this one...I have changed some lines in pix2pix i should try deleting and unzip the project again...Thanks:)

**Comment by javirk** [comment]
Thank you for your help, @Kunika21. @naganikshith04, there is a PR waiting for approval with a link to a Google Colab notebook: https://colab.research.google.com/drive/1JDpH8MAjaKoekQ_H9ZaxYJ9_axiDtDGm?usp=sharing Maybe that can help you.

**Comment by naganikshith04** [comment]
> Thank you for your help, @Kunika21. @naganikshith04, there is a PR waiting for approval with a link to a Google Colab notebook: https://colab.research.google.com/drive/1JDpH8MAjaKoekQ_H9ZaxYJ9_axiDtDGm?usp=sharing Maybe that can help you.

Thanks,@javirk this will be real help...thank you very much😁

**Comment by Daryl149** [comment]
> > Thank you for your help, @Kunika21. @naganikshith04, there is a PR waiting for approval with a link to a Google Colab notebook: https://colab.research.google.com/drive/1JDpH8MAjaKoekQ_H9ZaxYJ9_axiDtDGm?usp=sharing Maybe that can help you.
> 
> Thanks,@javirk this will be real help...thank you very much😁

For the colab, keep in mind that you need to replace the cell where the repo is cloned with my fork instead: https://github.com/Daryl149/Person_remover.git
The original repo won't work (or requires a small manual change) with the colab until the PR has been merged.
